service: purescript-lambda

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  deploymentBucket: lwb-test-serverless-deploys

package:
  include:
    - ouput/**

functions:
  basic:
    handler: src/index.basic
  event:
    handler: src/index.event
