service: purescript-lambda

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  deploymentBucket: lwb-test-serverless-deploys

package:
  include:
    - output/**

functions:
  basic:
    handler: output/Basic.handler
  event:
    handler: output/Event.handler
